app:
  test: arbitrary_value
  scheduler:
    interval: PT10S
    checkIndent: PT1000S

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 8088