app:
  test: arbitrary_value
  scheduler:
    interval: PT10S
    checkIndent: PT1000S
  database-access-type: jpa
  rabbit-mq-info:
    update-queue-name: updatesQueue
    exchange-name: directExchange
    updates-routing-key: updates
  use-queue: true

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8088

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info,prometheus"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true