app:
  test: arbitrary_value
  tgCredentials:
    token: ${BOT_TOKEN}
  rabbit-mq-info:
    update-queue-name: updatesQueue
    exchange-name: directExchange
    updates-routing-key: updates

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,info,prometheus"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true