version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
     image: liquibase/liquibase:4.18
     depends_on:
         - postgresql
     command:
         - --hub-mode=off
         - --changelog-file=master.xml
         - --driver=org.postgresql.Driver
         - --url=jdbc:postgresql://postgresql:5432/scrapper
         - --username=postgres
         - --password=postgres
         - update
     volumes:
         - ./migrations:/liquibase/changelog
     networks:
         - backend

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - backend

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - backend

volumes:
  postgres:
    driver: local
  rabbitmq:
  prometheus:
  grafana:

networks:
  backend:
    driver: bridge